id: PAC245BC5
initial_creation_type: input
source_metadata:
  title: Śāntideva Series
  language: de
  description: 'Texts by and about the Indian master Śāntideva (zhi ba lha), renowned
    author of the Bodhicaryāvatāra:'
  volume:
    ed33191b1fbc4c6aa5584fbe5df8d066:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    80fac0ec993f4a6a9dcfea389e228589:
      title: 'Bodhicaryāvatāra—Chapter 1: The Benefits of Bodhicitta'
      parent: Bodhicaryāvatāra Root Text
    8e2816ff2d774500abc882f27ff395b0:
      title: 'Bodhicaryāvatāra—Chapter 2: Confession of Negativity'
      parent: Bodhicaryāvatāra Root Text
    66685edd51be41469afc16f01da9c9c9:
      title: 'Bodhicaryāvatāra—Chapter 3: Fully Adopting Bodhicitta'
      parent: Bodhicaryāvatāra Root Text
    1a5e393007e943caa3710ff852a0476f:
      title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
      parent: Prayers
created_at: '2022-03-01T02:22:42.793097'
last_modified_at: '2022-03-01T02:22:42.793101'
